### PR TITLE
Add a namespace for the backend`s resources, for example: `backend` or `admin`

### LINKED ISSUE #391: I have app/styles/app.scss, but I still get the error "app/styles/app.[scss/sass does not exist]"
Hi,
My code: https://github.com/onecoinim/ember-cli-cms 

I have updated the ember-cli to v0.2.5 which is the same as ember-cli-admin.

Who can help me?
Thanks.

### PR DESCRIPTION
**Pull request by mojied**
`Ember-cli-admin` is prominent. This PR closed #391 , and changed the metaRoute, let us 
generates URLs with a default namespace 'backend',  you can change it by using
a `path` option as the follow:

```javascript
MetaRoute.map(Router, {path: "/admin"}, function() {
    this.route("dashboard"); //This will generate '/admin/dashboeard'
    this.resources("users");
});
```
This let the backend and frontend completely isolated, and let us focus on the development of the backend.

### CODE REVIEW

**Comment by igorrKurr** [comment]
Hi!

Thanks for PR!
It seems to be good and brings us useful features, but as for me it will be better if default namespace will be not 'backend', but 'admin', and also maybe we need to make this feature optional (like some flag in config), because in many projects ember-cli-admin was used just like separate admin board, without any other parts.
@OpakAlex what do think about?

**Comment by OpakAlex** [comment]
yes, backend not good....

**Comment by mojied** [comment]
Then, had better no default namespace. Developers can add a namespace `admin` by adding `{path: ‘admin‘}`，like `Ember.Router`. What do you think about?

**Comment by OpakAlex** [comment]
yes, if you remove default namespace it's will be good!

**Comment by mojied** [comment]
Now, It has no default namespace, but can be added by giving a `path` option. Only one thing is that the `index` and the `dashboard` are all "/".

**Comment by OpakAlex** [comment]
thanks!!

**Pull request merged**
